language: java
jdk:
  - openjdk11

branches:
  only:
    - master
    -
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - chmod +x gradlew
  - zip -r study-springboot2-webservice *
  - mkdir -p deploy
  - mv study-springboot2-webservice.zip deploy/study-springboot2-websservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값

    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값

    bucket: study-springboot2-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에 생성한 디렉토리
    wait-until-deploy: true

# CI 실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - wkdrn970@naver.com